name       : python-neovim
version    : 0.1.11
release    : 1
source     :
    - https://github.com/neovim/python-client/archive/0.1.11.tar.gz : 7ca99d14aa364efc5d3c8ecefd31af16a9c5c93ebe7cd1b2fa64717b74a76d50
license    : Apache-2.0
component  : programming.python
summary    : Python client for Neovim
description: |
    Python client for Neovim
builddeps  :
    - python-setuptools
rundeps    :
    - neovim
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
