name       : python-neovim
version    : 0.2.3
release    : 8
source     :
    - https://github.com/neovim/python-client/archive/0.2.3.tar.gz : 12dd8f4fd9b2ff43f245eba1655f7c0a0e5fb9bd85861e7b62027189a47b398a
license    : Apache-2.0
component  : programming.python
summary    : Python client for Neovim
description: |
    Python client for Neovim
builddeps  :
    - python-setuptools
rundeps    :
    - neovim
    - python-greenlet
    - python-msgpack
    - python-trollius
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
