name       : python-neovim
version    : 0.3.1
release    : 11
source     :
    - https://github.com/neovim/pynvim/archive/0.3.1.tar.gz : 055aa44b601e4b0d3aa923ed8e523a483200ad9f08965aa9b46d55ac0ebacb94
license    : Apache-2.0
component  : programming.python
summary    : Python client for Neovim
description: |
    Python client for Neovim
builddeps  :
    - python-setuptools
rundeps    :
    - neovim
    - python-greenlet
    - python-msgpack
    - python-trollius
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
