name       : python-neovim
version    : 0.3.2
release    : 12
source     :
    - https://github.com/neovim/pynvim/archive/0.3.2.tar.gz : 0a44c540dd5790acfbc7e411b0ed4fb6c44914d866226ebebf370c24c2723dc2
license    : Apache-2.0
component  : programming.python
summary    : Python client for Neovim
description: |
    Python client for Neovim
builddeps  :
    - python-setuptools
rundeps    :
    - neovim
    - python-greenlet
    - python-msgpack
    - python-trollius
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
