name       : python-neovim
version    : 0.4.3
release    : 17
source     :
    - https://github.com/neovim/pynvim/archive/refs/tags/0.4.3.tar.gz : e7c9de44b0201ad874a608270b7a9b10fd48bda65f49bada05815d973ca79391
license    : Apache-2.0
component  : programming.python
summary    : Python client for Neovim
description: |
    Python client for Neovim
rundeps    :
    - neovim
    - python-greenlet
    - python-msgpack
build      : |
    %python3_setup
install    : |
    %python3_install
