name       : python-neovim
version    : 0.1.12
release    : 2
source     :
    - https://github.com/neovim/python-client/archive/0.1.12.tar.gz : a0ec9d157d385d86c2a07f9f9daa20cc172160d1782bf9a40d8e9724a01026c1
license    : Apache-2.0
component  : programming.python
summary    : Python client for Neovim
description: |
    Python client for Neovim
builddeps  :
    - python-setuptools
rundeps    :
    - neovim
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
