name       : python-neovim
version    : 0.4.1
release    : 15
source     :
    - https://github.com/neovim/pynvim/archive/0.4.1.tar.gz : 132ea5c226399aed45a959f1d8efe8cdd89a769a672534722760a9a67b06dfa0
license    : Apache-2.0
component  : programming.python
summary    : Python client for Neovim
description: |
    Python client for Neovim
rundeps    :
    - neovim
    - python-greenlet
    - python-msgpack
build      : |
    %python3_setup
install    : |
    %python3_install
